#!/usr/bin/env python

import os
import sys
import argparse
import matplotlib
matplotlib.use("MacOSX")
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np

def update_figure(num,directory,data_prefix,ndigits):
    #pad with zeros up to ndigits
    padstring = "%0"+str(ndigits)+"d.npz"

    #grab current data from its .npz file
    currFile = os.path.join(directory,data_prefix+(padstring % (num+1)))
    data = np.load(currFile)['arr_0']

    #clear axis and replot
    im.set_data(data)

    #return image object
    return im

def main(args):
    #get directory in which movie data is being saved
    directory = args.directory
    outfile = args.outfile

    #get file prefix (default for now until argparse is implemented)
    prefix = "frame"

    #count number of files in this directory
    fullpath = os.path.join(os.getcwd(),directory)
    nfiles = len(os.listdir(fullpath))
    ndigits = np.ceil(np.log10(nfiles))+1

    #initialize frame counter variable
    update_figure.frame_counter = 0 

    #make figure window
    fig = plt.figure()
    ax = fig.add_subplot(1,1,1)

    #fetch data for first frame
    padstring = "%0"+str(ndigits)+"d.npz"
    firstFile = os.path.join(directory,prefix+(padstring % 0))
    firstData = np.load(firstFile)['arr_0']
    
    #make a global variable for first frame image (clunky, but works for now)
    global im
    im = ax.imshow(firstData,cmap=plt.get_cmap('YlGnBu'),interpolation='none')
    
    #make animation
    movie = animation.FuncAnimation(fig,update_figure,fargs=(directory,prefix,ndigits),
                                    frames=nfiles-1,interval=args.interval,blit=True)

    #initialize filewriter and write movie to file
    MovieWriter = animation.writers['ffmpeg']
    mwriter = MovieWriter(fps=args.fps)
    movie.save("%s.mp4" % outfile, writer=mwriter)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Movie Writer for Monte Carlo frames generated by ising.py")
    parser.add_argument('directory',type=str,help="directory that movie data is stored in")
    parser.add_argument('-o','--outfile',type=str,default='movie',help="name of .mp4 file to write out (default = movie.mp4)")
    parser.add_argument('-i','--interval',type=int,default=20,help="frame redrawing interval")
    parser.add_argument('-f','--fps',type=int,default=60,help="movie framerate")
    args = parser.parse_args()
    main(args)
